from secrets import TWITTER_APP_KEY, TWITTER_APP_SECRET, OAUTH_TOKEN, OAUTH_TOKEN_SECRET

from twython import Twython

APP_KEY = TWITTER_APP_KEY
APP_SECRET = TWITTER_APP_SECRET
TOKEN = OAUTH_TOKEN
TOKEN_SECRET = OAUTH_TOKEN_SECRET

twitter = Twython(APP_KEY, APP_SECRET, TOKEN, TOKEN_SECRET)