a = {'id': 2862904287, 'id_str': '2862904287', 'name': 'Gabi aka nullos 1er', 'screen_name': 'DUGNYCHON',
     'location': 'ahhh', 'description': 'cat no banana', 'url': None, 'entities': {'description': {'urls': []}},
     'protected': False, 'followers_count': 206, 'friends_count': 208, 'listed_count': 1,
     'created_at': 'Wed Nov 05 18:04:48 +0000 2014', 'favourites_count': 5490, 'utc_offset': 7200, 'time_zone': 'Paris',
     'geo_enabled': True, 'verified': False, 'statuses_count': 10568, 'lang': 'fr',
     'status': {'created_at': 'Fri May 12 14:50:45 +0000 2017', 'id': 863043774640992257,
                'id_str': '863043774640992257', 'text': 'bourgeoisie cat https://t.co/d9SuI41Wkl', 'truncated': False,
                'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
                    {'url': 'https://t.co/d9SuI41Wkl',
                     'expanded_url': 'https://twitter.com/lmfaogtfoo/status/863041613395886080',
                     'display_url': 'twitter.com/lmfaogtfoo/sta…', 'indices': [16, 39]}]},
                'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
                'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'geo': None, 'coordinates': None,
                'place': None, 'contributors': None, 'is_quote_status': True, 'quoted_status_id': 863041613395886080,
                'quoted_status_id_str': '863041613395886080', 'retweet_count': 2, 'favorite_count': 3,
                'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'lang': 'fr'},
     'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
     'profile_background_color': '000000',
     'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
     'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
     'profile_background_tile': False,
     'profile_image_url': 'http://pbs.twimg.com/profile_images/852591994614558722/WfKXBaed_normal.jpg',
     'profile_image_url_https': 'https://pbs.twimg.com/profile_images/852591994614558722/WfKXBaed_normal.jpg',
     'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2862904287/1491862723',
     'profile_link_color': '000000', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000',
     'profile_text_color': '000000', 'profile_use_background_image': False, 'has_extended_profile': True,
     'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False,
     'notifications': False, 'translator_type': 'regular'}
b = {'id': 2862904287, 'id_str': '2862904287', 'name': 'Gabi aka nullos 1er',
     'screen_name': 'DUGNYCHON', 'location': 'ahhh',
     'description': 'cat no banana', 'url': None,
     'entities': {'description': {'urls': []}}, 'protected': False,
     'followers_count': 206, 'friends_count': 208, 'listed_count': 1,
     'created_at': 'Wed Nov 05 18:04:48 +0000 2014', 'favourites_count': 5490,
     'utc_offset': 7200, 'time_zone': 'Paris', 'geo_enabled': True,
     'verified': False, 'statuses_count': 10568, 'lang': 'fr',
     'status': {'created_at': 'Fri May 12 14:50:45 +0000 2017',
                'id': 863043774640992257, 'id_str': '863043774640992257',
                'text': 'bourgeoisie cat https://t.co/d9SuI41Wkl',
                'truncated': False,
                'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [],
                             'urls': [{'url': 'https://t.co/d9SuI41Wkl',
                                       'expanded_url': 'https://twitter.com/lmfaogtfoo/status/863041613395886080',
                                       'display_url': 'twitter.com/lmfaogtfoo/sta…',
                                       'indices': [16, 39]}]},
                'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
                'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None,
                'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
                'in_reply_to_screen_name': None, 'geo': None,
                'coordinates': None, 'place': None, 'contributors': None,
                'is_quote_status': True, 'quoted_status_id': 863041613395886080,
                'quoted_status_id_str': '863041613395886080', 'retweet_count': 2,
                'favorite_count': 3, 'favorited': False, 'retweeted': False,
                'possibly_sensitive': False, 'lang': 'fr'},
     'contributors_enabled': False, 'is_translator': False,
     'is_translation_enabled': False, 'profile_background_color': '000000',
     'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
     'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
     'profile_background_tile': False,
     'profile_image_url': 'http://pbs.twimg.com/profile_images/852591994614558722/WfKXBaed_normal.jpg',
     'profile_image_url_https': 'https://pbs.twimg.com/profile_images/852591994614558722/WfKXBaed_normal.jpg',
     'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2862904287/1491862723',
     'profile_link_color': '000000', 'profile_sidebar_border_color': '000000',
     'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
     'profile_use_background_image': False, 'has_extended_profile': True,
     'default_profile': False, 'default_profile_image': False,
     'following': False, 'follow_request_sent': False, 'notifications': False,
     'translator_type': 'regular'}
c = {'id': 3010414262, 'id_str': '3010414262', 'name': '!', 'screen_name': 'sarabricot', 'location': 'she/her',
     'description': "i'm a samurai princess i'll smash you", 'url': None, 'entities': {'description': {'urls': []}},
     'protected': False, 'followers_count': 867, 'friends_count': 522, 'listed_count': 22,
     'created_at': 'Thu Feb 05 17:18:20 +0000 2015', 'favourites_count': 20010, 'utc_offset': 7200,
     'time_zone': 'Belgrade', 'geo_enabled': True, 'verified': False, 'statuses_count': 37955, 'lang': 'fr',
     'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': True,
     'profile_background_color': 'C0DEED',
     'profile_background_image_url': 'http://pbs.twimg.com/profile_background_images/678160666608406528/0LAWjyv8.jpg',
     'profile_background_image_url_https': 'https://pbs.twimg.com/profile_background_images/678160666608406528/0LAWjyv8.jpg',
     'profile_background_tile': False,
     'profile_image_url': 'http://pbs.twimg.com/profile_images/858640295243776000/k7ZjhTFL_normal.jpg',
     'profile_image_url_https': 'https://pbs.twimg.com/profile_images/858640295243776000/k7ZjhTFL_normal.jpg',
     'profile_banner_url': 'https://pbs.twimg.com/profile_banners/3010414262/1474203411',
     'profile_link_color': 'F1C4D3', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000',
     'profile_text_color': '000000', 'profile_use_background_image': True, 'has_extended_profile': True,
     'default_profile': False, 'default_profile_image': False, 'following': True, 'follow_request_sent': False,
     'notifications': False, 'translator_type': 'none'}
