a = {'id': 2862904287, 'id_str': '2862904287', 'name': 'Gabi aka nullos 1er', 'screen_name': 'DUGNYCHON',
     'location': 'ahhh', 'description': 'cat no banana', 'url': None, 'entities': {'description': {'urls': []}},
     'protected': False, 'followers_count': 206, 'friends_count': 208, 'listed_count': 1,
     'created_at': 'Wed Nov 05 18:04:48 +0000 2014', 'favourites_count': 5490, 'utc_offset': 7200, 'time_zone': 'Paris',
     'geo_enabled': True, 'verified': False, 'statuses_count': 10568, 'lang': 'fr',
     'status': {'created_at': 'Fri May 12 14:50:45 +0000 2017', 'id': 863043774640992257,
                'id_str': '863043774640992257', 'text': 'bourgeoisie cat https://t.co/d9SuI41Wkl', 'truncated': False,
                'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [
                    {'url': 'https://t.co/d9SuI41Wkl',
                     'expanded_url': 'https://twitter.com/lmfaogtfoo/status/863041613395886080',
                     'display_url': 'twitter.com/lmfaogtfoo/sta…', 'indices': [16, 39]}]},
                'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
                'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'geo': None, 'coordinates': None,
                'place': None, 'contributors': None, 'is_quote_status': True, 'quoted_status_id': 863041613395886080,
                'quoted_status_id_str': '863041613395886080', 'retweet_count': 2, 'favorite_count': 3,
                'favorited': False, 'retweeted': False, 'possibly_sensitive': False, 'lang': 'fr'},
     'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False,
     'profile_background_color': '000000',
     'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
     'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
     'profile_background_tile': False,
     'profile_image_url': 'http://pbs.twimg.com/profile_images/852591994614558722/WfKXBaed_normal.jpg',
     'profile_image_url_https': 'https://pbs.twimg.com/profile_images/852591994614558722/WfKXBaed_normal.jpg',
     'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2862904287/1491862723',
     'profile_link_color': '000000', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000',
     'profile_text_color': '000000', 'profile_use_background_image': False, 'has_extended_profile': True,
     'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False,
     'notifications': False, 'translator_type': 'regular'}
b = {'id': 866905967463714820, 'id_str': '866905967463714820', 'name': 'ISN Test', 'screen_name': 'isn_test',
     'location': 'Ile-de-France, France', 'description': 'Un petit compte pour tester Twysn tranquillement !',
     'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 1,
     'friends_count': 65, 'listed_count': 0, 'created_at': 'Tue May 23 06:37:43 +0000 2017', 'favourites_count': 1,
     'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 1, 'lang': 'fr',
     'status': {'created_at': 'Tue May 23 06:46:12 +0000 2017', 'id': 866908102532222977,
                'id_str': '866908102532222977',
                'text': "RT @EmmanuelMacron: J'adresse mes pensées au peuple britannique, aux victimes et à leurs proches. Nous menons ensemble le combat contre le…",
                'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [
             {'screen_name': 'EmmanuelMacron', 'name': 'Emmanuel Macron', 'id': 1976143068, 'id_str': '1976143068',
              'indices': [3, 18]}], 'urls': []},
                'source': '<a href="https://github.com/SoFolichon/ISN-Twitter" rel="nofollow">Twysn</a>',
                'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
                'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'geo': None, 'coordinates': None,
                'place': None, 'contributors': None,
                'retweeted_status': {'created_at': 'Tue May 23 06:45:13 +0000 2017', 'id': 866907853239484416,
                                     'id_str': '866907853239484416',
                                     'text': "J'adresse mes pensées au peuple britannique, aux victimes et à leurs proches. Nous menons ensemble le combat contre le terrorisme.",
                                     'truncated': False,
                                     'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []},
                                     'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                                     'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None,
                                     'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None,
                                     'in_reply_to_screen_name': None, 'geo': None, 'coordinates': None, 'place': None,
                                     'contributors': None, 'is_quote_status': False, 'retweet_count': 827,
                                     'favorite_count': 1261, 'favorited': True, 'retweeted': True, 'lang': 'fr'},
                'is_quote_status': False, 'retweet_count': 827, 'favorite_count': 0, 'favorited': True,
                'retweeted': True, 'lang': 'fr'}, 'contributors_enabled': False, 'is_translator': False,
     'is_translation_enabled': False, 'profile_background_color': '000000',
     'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
     'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
     'profile_background_tile': False,
     'profile_image_url': 'http://pbs.twimg.com/profile_images/866906968539234304/k4cugQgp_normal.jpg',
     'profile_image_url_https': 'https://pbs.twimg.com/profile_images/866906968539234304/k4cugQgp_normal.jpg',
     'profile_link_color': '19CF86', 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000',
     'profile_text_color': '000000', 'profile_use_background_image': False, 'has_extended_profile': False,
     'default_profile': False, 'default_profile_image': False, 'following': False, 'follow_request_sent': False,
     'notifications': False, 'translator_type': 'none'}
c = b
