a = {'id': 2862904287, 'id_str': '2862904287', 'name': 'nullos 1er', 'screen_name': 'DUGNYCHON', 'location': 'ahhh',
 'description': 'aaaaaaahhhhh.......', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False,
 'followers_count': 206, 'friends_count': 208, 'listed_count': 2, 'created_at': 'Wed Nov 05 18:04:48 +0000 2014',
 'favourites_count': 5252, 'utc_offset': 7200, 'time_zone': 'Paris', 'geo_enabled': True, 'verified': False,
 'statuses_count': 9956, 'lang': 'fr',
 'status': {'created_at': 'Sun Apr 16 18:56:36 +0000 2017', 'id': 853683561794326528, 'id_str': '853683561794326528',
            'text': 'bonjour', 'truncated': False,
            'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []},
            'source': '<a href="https://github.com/SoFolichon/ISN-Twitter" rel="nofollow">ISNProject</a>',
            'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None,
            'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'geo': None, 'coordinates': None,
            'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0,
            'favorited': False, 'retweeted': False, 'lang': 'fr'}, 'contributors_enabled': False,
 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': '000000',
 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
 'profile_background_tile': False,
 'profile_image_url': 'http://pbs.twimg.com/profile_images/852591994614558722/WfKXBaed_normal.jpg',
 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/852591994614558722/WfKXBaed_normal.jpg',
 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2862904287/1491862723', 'profile_link_color': '000000',
 'profile_sidebar_border_color': '000000', 'profile_sidebar_fill_color': '000000', 'profile_text_color': '000000',
 'profile_use_background_image': False, 'has_extended_profile': True, 'default_profile': False,
 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False,
 'translator_type': 'regular'}
